services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    networks:
      - ecom-network


  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - ecom-network


  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - ecom-network


  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - discovery-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - ecom-network


  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - discovery-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - ecom-network


  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - discovery-server
      - product-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - ecom-network


volumes:
  mysql-data:


networks:
  ecom-network: